service: imganalysis

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  recognize:
    handler: bin/recognize
    events:
      - http:
          path: recognize
          method: post