service: imganalysis

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rekognition:DetectLabels
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  recognize:
    handler: bin/recognize
    events:
      - http:
          path: recognize
          method: post
          private: false